// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagementSystem.Data;

#nullable disable

namespace SalesManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesManagementSystem.Models.SaleAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AccountType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("PlatformId");

                    b.ToTable("SaleAccount", (string)null);
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleAcct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("AmazonFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmzProRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FromAccountId")
                        .HasColumnType("int");

                    b.Property<string>("OrderID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("OtherCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProfitAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("ISNULL(SoldAmount,0) - ISNULL(CostAmount,0) - ISNULL(TotalProCharges,0) - ISNULL(AmazonFee,0) - ISNULL(OtherCharges,0) + ISNULL(TotalRroRebate,0)", true);

                    b.Property<decimal?>("QtyHeld")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("QtySold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SoldAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("StatusID")
                        .HasColumnType("int");

                    b.Property<int?>("ToAccountId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalProCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalPromotion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalRroRebate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromAccountId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StatusID");

                    b.HasIndex("ToAccountId");

                    b.HasIndex("TransactionId");

                    b.ToTable("SaleAcct", (string)null);
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleCharge", b =>
                {
                    b.Property<long>("SaleChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SaleChargeId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ChargeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint");

                    b.HasKey("SaleChargeId");

                    b.HasIndex("ChargeTypeId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleCharge", (string)null);
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleChargeType", b =>
                {
                    b.Property<int>("ChargeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChargeTypeId"));

                    b.Property<string>("ChargeTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ChargeTypeId");

                    b.ToTable("SaleChargeType", (string)null);
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleDate", b =>
                {
                    b.Property<int>("SaleDateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleDateId"));

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SoldDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TransDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SaleDateId");

                    b.ToTable("SaleDate");
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SalePlatform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PlatformId");

                    b.ToTable("SalePlatform", (string)null);
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProductId");

                    b.HasIndex("PlatformId");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusID");

                    b.ToTable("SaleStatus", (string)null);
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleTransactionDate", b =>
                {
                    b.Property<int>("SaleTransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleTransId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("SaleAcctId")
                        .HasColumnType("bigint");

                    b.Property<int>("SaleDateId")
                        .HasColumnType("int");

                    b.HasKey("SaleTransId");

                    b.HasIndex("SaleAcctId");

                    b.HasIndex("SaleDateId");

                    b.ToTable("SaleTransactionDates");
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleTransactionType", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TransactionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TransactionId");

                    b.ToTable("SaleTransactionType", (string)null);
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleAccount", b =>
                {
                    b.HasOne("SalesManagementSystem.Models.SalePlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleAcct", b =>
                {
                    b.HasOne("SalesManagementSystem.Models.SaleAccount", "FromAccount")
                        .WithMany()
                        .HasForeignKey("FromAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SalesManagementSystem.Models.SalePlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId");

                    b.HasOne("SalesManagementSystem.Models.SaleProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("SalesManagementSystem.Models.SaleStatus", "StatusMaster")
                        .WithMany()
                        .HasForeignKey("StatusID");

                    b.HasOne("SalesManagementSystem.Models.SaleAccount", "ToAccount")
                        .WithMany()
                        .HasForeignKey("ToAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SalesManagementSystem.Models.SaleTransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionId");

                    b.Navigation("FromAccount");

                    b.Navigation("Platform");

                    b.Navigation("Product");

                    b.Navigation("StatusMaster");

                    b.Navigation("ToAccount");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleCharge", b =>
                {
                    b.HasOne("SalesManagementSystem.Models.SaleChargeType", "ChargeType")
                        .WithMany()
                        .HasForeignKey("ChargeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesManagementSystem.Models.SaleAcct", "Sale")
                        .WithMany("Charges")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargeType");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleProduct", b =>
                {
                    b.HasOne("SalesManagementSystem.Models.SalePlatform", "Platform")
                        .WithMany("Products")
                        .HasForeignKey("PlatformId");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleTransactionDate", b =>
                {
                    b.HasOne("SalesManagementSystem.Models.SaleAcct", "SaleAcct")
                        .WithMany()
                        .HasForeignKey("SaleAcctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesManagementSystem.Models.SaleDate", "SaleDate")
                        .WithMany("SaleTransactionDates")
                        .HasForeignKey("SaleDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleAcct");

                    b.Navigation("SaleDate");
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleAcct", b =>
                {
                    b.Navigation("Charges");
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SaleDate", b =>
                {
                    b.Navigation("SaleTransactionDates");
                });

            modelBuilder.Entity("SalesManagementSystem.Models.SalePlatform", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
